server:
  auth_port: 8001
  queue_port: 8002
  booking_port: 8003
  websocket_port: 8004
  station_port: 8006
  printer_port: 8005
  
database:
  host: localhost
  port: 5432
  user: ivan
  password: Lost2409
  dbname: louaj_node
  sslmode: disable
  max_connections: 100
  min_connections: 10

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 10

jwt:
  secret_key: "yzUcAoaEZKUKdGp1rCxZQXo3nXFKuyGnsF3G4GcxE6YKKlOwGbzgdualz+B0T8z4Pg00OOZqYS+NYZGvZeVouA=="
  expiration_hours: 24

cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Content-Type"
    - "Authorization"
